app/models/__init__.py
from .database import db
from .records import RecordsModel

app/models/database.py
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

app/models/records.py
from .database import db

 
class RecordsModel(db.Model):
    __tablename__ = 'records'
 
    id = db.Column(db.Integer, primary_key = True, autoincrement=True)
    starting_point = db.Column(db.Float)
    week_1 = db.Column(db.Float)
    week_2 = db.Column(db.Float)
    week_3 = db.Column(db.Float)
    week_4 = db.Column(db.Float)
    week_5 = db.Column(db.Float)
    week_6 = db.Column(db.Float)
    week_7 = db.Column(db.Float)
    week_8 = db.Column(db.Float)
    week_9 = db.Column(db.Float)
    week_10 = db.Column(db.Float)
 
    def __init__(self, starting_point, week_1, week_2, week_3, week_4, week_5, week_6, week_7, week_8, week_9, week_10):
        self.starting_point = starting_point
        self.week_1 = week_1
        self.week_2 = week_2
        self.week_3 = week_3
        self.week_4 = week_4
        self.week_5 = week_5
        self.week_6 = week_6
        self.week_7 = week_7
        self.week_8 = week_8
        self.week_9 = week_9
        self.week_10 = week_10
 
    def __repr__(self):
        return f"Starting point: {self.starting_point}"

app/__init__.py
import os
import sys
from dotenv import load_dotenv
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.exc import OperationalError
from flask_migrate import Migrate

from app.routes.main_routes import main_bp
from app.models import db, RecordsModel


load_dotenv()

# Application factory
def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = (
        f"postgresql://{os.getenv('POSTGRES_USER')}"
        f":{os.getenv('POSTGRES_PASSWORD')}"
        f"@{os.getenv('POSTGRES_HOST')}"
        f":{os.getenv('POSTGRES_PORT')}"
        f"/{os.getenv('POSTGRES_DB')}"
    )
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    # Set up database configuration
    db.init_app(app)

    # Initialize flask-migrate
    migrate = Migrate(app, db)
    
    # Test that the database connection works
    try:    
        with app.app_context():
            RecordsModel.query.first()
            print("\nSuccessfully conncted to database")
    except OperationalError as e:
        # Terminate the program if the database connection is faulty
        print(f"Invalid database connection settings: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error (Database connection): {e}")
        sys.exit(1)
    
    app.register_blueprint(main_bp)

    return app


app = create_app()

app/routes/main_routes.py
from flask import Blueprint, render_template, request
from app.models import db, RecordsModel
from app.utils.graph_generator import generate_graph, generate_weight_graph, generate_weight_graph_gif
from app.utils.form_data_support import weight_input_transform
from collections import OrderedDict

main_bp = Blueprint("main", __name__)

@main_bp.route("/")
def home():
    generate_graph()
    return render_template("pages/home.html")

@main_bp.route("/about")
def about():
    return render_template("pages/about.html")

@main_bp.route("/weight_form", methods = ['POST', 'GET'])
def weight_form():
    if request.method == 'GET':
        return render_template("pages/weight_form.html")
    
    if request.method == 'POST':
        # Create an ordered dict to hold the form data
        ordered_data = weight_input_transform(request.form)

        # Check ordered_data for correct type
        if not isinstance(ordered_data, OrderedDict):
            error_message = "Error: Input must be an OrderedDict"
            print(error_message)
            return render_template("pages/error.html", message=error_message)

        # Begin a database transaction
        db.session.begin()

        try:
            # Store in database
            weight_data = RecordsModel(*list(ordered_data.values()))
            db.session.add(weight_data)
        except Exception as e:
            print(f"An error occurred: {e}")
            db.session.rollback()
            return render_template("pages/error.html", message=str(e))
        else:
            # Commit the transaction if no exceptions occurred
            db.session.commit()
            generate_weight_graph(list(ordered_data.values()))
            generate_weight_graph_gif(list(ordered_data.values()))


        return render_template("pages/user_graph.html")

app/templates/_navigation.html
<nav>
    <ul>
      <li><a href="{{ url_for('main.home') }}">Home</a></li>
      <li><a href="{{ url_for('main.about') }}">About</a></li>
      <li><a href="{{ url_for('main.weight_form') }}">Weight graph</a></li>
    </ul>
  </nav>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Body Measurements - {% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style2.css') }}">
</head>
<body>
<h1>Body Measurements</h1>
{% include("_navigation.html") %}
<section>
  <header>
    {% block header %}{% endblock header %}
  </header>
  <main>
    {% block content %}<p>No messages.</p>{% endblock content %}
  </main>
</section>
</body>
</html>

app/templates/pages/about.html
{% extends 'base.html' %}

{% block header %}
  <h2>{% block title %}About{% endblock title %}</h2>
{% endblock header %}

{% block content %}
  <p>Flask project that allows user to enter their weight progress and get a graph returned</p><br>
  <p>Using SQL Alchemy to connect to PostreSQL database</p><br>
  <p>Created by Simon Janlöv</p>
{% endblock content %}

app/templates/pages/error.html
{% extends 'base.html' %}

{% block header %}
  <h2>{% block title %}Error{% endblock title %}</h2>
{% endblock header %}

{% block content %}
  <p>An error occured</p><br>
  <p>{{ message }}</p>
{% endblock content %}

app/templates/pages/home.html
{% extends 'base.html' %}

{% block header %}
  <h2>{% block title %}Home{% endblock title %}</h2>
{% endblock header %}

{% block content %}
  <p>Go to "weight graph" to track your progress.</p><br>
  <p>Learn more about this project by visiting the <a href="{{ url_for('main.about') }}">About page</a>.</p>
  
  <!-- <div class="image-container">
    <img src="{{ url_for('static', filename='img/graph.png') }}"> 
  </div> -->
{% endblock content %}

app/templates/pages/submit_weight.html
{% extends "base.html" %}

{% block header %}
  <h2>Submit Your Weight</h2>
{% endblock header %}

{% block content %}
  <form action="{{ url_for('main.submit_weight') }}" method="post">
    <label for="starting_point">Starting Point:</label>
    <input type="number" id="starting_point" name="starting_point" required><br>

    {% for week in range(1, 11) %}
      <label for="week_{{ week }}">Week {{ week }}:</label>
      <input type="number" id="week_{{ week }}" name="week_{{ week }}" required><br>
    {% endfor %}

    <input type="submit" value="Submit">
  </form>
{% endblock content %}

app/templates/pages/user_graph.html
{% extends 'base.html' %}

{% block header %}
  <h2>{% block title %}Weight progression{% endblock title %}</h2>
{% endblock header %}

{% block content %}
  <div class="image-container">
    <!-- <img src="{{ url_for('static', filename='img/user_graph.png') }}"> -->
    <img src="{{ url_for('static', filename='img/user_graph.gif') }}"> 
  </div>
{% endblock content %}

app/templates/pages/weight_form.html
{% extends "base.html" %}

{% block header %}
  <h2>Enter weight information</h2>
{% endblock header %}

{% block content %}
  <form action="{{ url_for('main.weight_form') }}" method="post">
    <label for="starting_point">Starting Point:</label>
    <input type="number" id="starting_point" name="starting_point" step="0.01"><br>

    {% for week in range(1, 11) %}
      <label for="week_{{ week }}">Week {{ week }}:</label>
      <input type="number" id="week_{{ week }}" name="week_{{ week }}" step="0.01"><br>
    {% endfor %}

    <input type="submit" value="Submit">
  </form>
{% endblock content %}